knife4j:
  enable: true
  openapi:
    title: 学生管理接口文档
    description: "学生管理接口文档"
    email: 123@123.com
    concat: zhiend
    url: http://localhost:10086/doc.html
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - org.example.express_backend.controller